### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by guydelarea** [loctvl842/monokai-pro.nvim#10]
Hey! first of all thank you for this theme, its awesome!
one question though,
is there a way to change the font to some custom font? instead of the Mononoki Nerd Font?

**Comment by loctvl842** [comment]
Sorry, I don't use Monokai Nerd Font. Can you describe your problem clearer?

**Comment by guydelarea** [comment]
nvm it was a glitched in my terminal. thanks
