### ISSUE TITLE
Markdown highlighting bug

### ISSUE THREAD

**Issue by SimonTheoret** [loctvl842/monokai-pro.nvim#104]
Hi!
Currently, some highlights of markdown are still broken. For example, code blocks in markdown have a transparent background.

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/104704678/f6735a02-3fdb-4ab3-b9ea-6a5e7d78d765)

I believe the last commit did not fully fix the markdown issues. 
Thank you

**Comment by loctvl842** [comment]
Here is mine.

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/44be3635-db4a-47e1-bc0f-2a62e5bfa52e)

can you try the latest release? If the bug still there, please raise with `conceallevel=3`

**Comment by loctvl842** [comment]
Here is mine.

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/44be3635-db4a-47e1-bc0f-2a62e5bfa52e)

can you try the latest release? If the bug still there, please raise with `conceallevel=3`
