### ISSUE TITLE
Override colorscheme for plugin nvim-treesitter

### ISSUE THREAD

**Issue by lcheylus** [loctvl842/monokai-pro.nvim#113]
I'm using your monokai-pro colorscheme with Neovim (on Linux and OpenBSD) and I'm very happy with it :)

But with `nvim-treesitter.lua` plugin (also used with Neovim), I don't like italic style used for some items, especially for Markdown inline => https://github.com/loctvl842/monokai-pro.nvim/blob/master/lua/monokai-pro/theme/plugins/nvim-treesitter.lua

Is it possible and how could I override monokai-pro colorscheme for nvim-treesitter.lua plugin ? I would like to set `italic = false` for `@markup.italic.markdown_inline` and other items.

**Comment by loctvl842** [comment]
Yes sure you can use override function
