### ISSUE TITLE
Switch colors when hovering over pairs because difficult to see

### ISSUE THREAD

**Issue by Ces-D** [loctvl842/monokai-pro.nvim#12]
Is there a way to switch the colors when hovering over bracket or parenthesis pairs. The dark color for the cursor is difficult to follow when the brighter color is at the end of the pair. Currently using "pro" . 
<img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTI4YjkxMzMxOTYyYWQ3YTQwNGE0MjgyYjBkYzg0OGQxZGZjY2JkZSZjdD1n/ukWPaEkrFITVWFUn23/giphy.gif" />

**Comment by loctvl842** [comment]
Try this
```lua
require("monokai-pro").setup({
    override = function(c)
        return {
            MatchParen = {
              -- bg = hp.blend(c.base.blue, 0.2),
              -- bg = hp.lighten(c.base.white, -55),
              fg = c.base.yellow,
              bold = true,
              underline = true,
            }, -- The character under the cursor or just before it, if it is a paired bracket, and its match. |pi_paren.txt|
        }
    end,
})
```

Actually, I personally don't like the current highlight for MatchParen. I need more feedbacks.

**Comment by Ces-D** [comment]
Thank you for the snippet. In my opinion it looks way better and more importantly is easier to follow. The brighter color needs to be over the cursor since that's where the eye is drawn, otherwise I think I am at the end of the pair.

**Comment by loctvl842** [comment]
> Thank you for the snippet. In my opinion it looks way better and more importantly is easier to follow. The brighter color needs to be over the cursor since that's where the eye is drawn, otherwise I think I am at the end of the pair.

Ok, I'll fix it as default. You don't need to override it again. Thanks for your feedback
