### ISSUE TITLE
When used with Indent-Blankline.nvim the cursor sometimes disappears

### ISSUE THREAD

**Issue by Wa1tee** [loctvl842/monokai-pro.nvim#13]
When the cursor is between indent lines it turns invisible. Using the default config

**Comment by Wa1tee** [comment]
Here the cursor is visible
![visible](https://user-images.githubusercontent.com/16970617/222339856-5a3c0fa7-8d01-4768-bac3-7930580d55bb.png)

When moved to the adjacent position either left or right, the cursor disappears
![not_visible](https://user-images.githubusercontent.com/16970617/222339792-7f02b4fc-c91f-4310-9453-ce6a7863c681.png)

**Comment by loctvl842** [comment]
I guess the problem might be your terminal.
I'm using `kitty` terminal and It's seem normal to me
![test_fix13](https://user-images.githubusercontent.com/80513079/222351717-d3237f9f-aa9d-4a42-a34c-6dbb6654a4ef.png)
The picture above is your `neovim_config`

**Comment by Wa1tee** [comment]
Tried at work using xfce terminal and the same issue persists: Cursor disappears when it's between the indent lines. It's visible if it's on an indent line or over text but a whitespace between indent lines it disappears. Seems like Kitty terminal may passively fix whatever the issue is

**Comment by loctvl842** [comment]
Recommend you use `kitty`, I feel it is much faster. You can also take a look at `Monokai Pro` colorscheme for that terminal as well.
>Tried at work using xfce terminal and the same issue persists: Cursor disappears when it's between the indent lines. It's visible if it's on an indent line or over text but a whitespace between indent lines it disappears. Seems like Kitty terminal may passively fix whatever the issue is
About this, I installed `xfce terminal`, I understand the problem. The cursor didn't disappear. In block shape, it have the same color with the text under it and the `indentline` have a very light black; therefore, you can't see your cursor. You can try to set this in your neovim.
```lua
vim.opt.guicursor = "n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor",
``` 
combine with override function if you see the `Cursor` 's color is too light.

**Comment by Wa1tee** [comment]
Thanks, that option fixed it for me!

I'll check kitty out too

**Comment by Tyler-Barham** [comment]
You could add the following to your config after setting up this plugin
```
vim.cmd "highlight! link IndentBlanklineChar      Whitespace"
vim.cmd "highlight! link IndentBlanklineSpaceChar Whitespace"
```
It returns the indent-blankline char/spacechar highlighting to their defaults rather than using the definitions from `lua/monokai-pro/theme/plugins/indent_blankline.lua`.

**Comment by loctvl842** [comment]
> highlight! link IndentBlanklineChar      Whitespace

My colorscheme support override:
```lua
        override = function(c)
          return {
            IndentBlanklineChar = { link = "Whitespace" },
          }
        end,
```
But I wonder why you need to rewrite this?

**Comment by Tyler-Barham** [comment]
> But I wonder why you need to rewrite this?

Have updated my config to use `override` instead, thanks :smiley:

<sub>_*Needs to read docs more carefully_</sub>
