### ISSUE TITLE
colorcolumn isn't visible

### ISSUE THREAD

**Issue by PlaiyTiziano** [loctvl842/monokai-pro.nvim#14]
My colorcolumn seems to be invisible.

I've tried several things:
1. Change the `filter` but no setting seems to make the colorcolumn visible.
2. Set the colorcolumn manually by calling `:set colorcolumn=80`.

The colorcolumn is visible in any other theme so i'm guessing it has nothing to do with my terminal colors.
My config for the monokai-pro theme is pretty much the default one
```lua
require("monokai-pro").setup({
    filter = "octagon",
    plugins = {
        bufferline = {
            underline_selected = false,
            underline_visible = false,
        },
    },
})
```

Versions:
- nvim: v0.8.2
- alacritty: v0.11.0
- tmux: 3.3a

**Comment by loctvl842** [comment]
ah that is because I don't know why should we use colorcolumn. So I just make it have the same color with the background in order to make screen cleaner.
Temporarily you can try this:
```lua
require("monokai-pro").setup({
    filter = "octagon",
    plugins = {
        bufferline = {
            underline_selected = false,
            underline_visible = false,
        },
    },
    override = function(c)
        ColorColumn = {bg = c.base.dimmed3}   
    end
})
```

**Comment by PlaiyTiziano** [comment]
The suggestion didn't seem to work for me, however I made the colorcolumn visible by executing the code below:
```lua
vim.api.nvim_set_hl(0, "ColorColumn", { ctermbg = 0, bg = "#161821" })
```
