### ISSUE TITLE
Missing color in yaml files

### ISSUE THREAD

**Issue by marnas** [loctvl842/monokai-pro.nvim#15]
I seem to be having an issue with yaml files using this theme.

Basically the key part is shown as white instead of the classic red I got used to while using this theme on VS code.

Is this expected behavior or am I missing some config?

![image](https://user-images.githubusercontent.com/39352252/222894728-47badc26-2828-4f6a-9486-74cfa7c1e654.png)

**Comment by loctvl842** [comment]
I have just updated it. Please check out the latest commit.
![treesitter_@field](https://user-images.githubusercontent.com/80513079/222896380-2093d2c9-918f-4229-a92f-ce5a7ffdc4d9.png)

**Comment by marnas** [comment]
Amazing, thank you!

**Comment by marnas** [comment]
I seem to be facing the same issue again, has anything changed?

**Comment by loctvl842** [comment]
I resolved it in the latest version, it's been a while since my last update

**Comment by marnas** [comment]
That fixed it, thank you!
