### ISSUE TITLE
Vertical column hidden

### ISSUE THREAD

**Issue by marnas** [loctvl842/monokai-pro.nvim#16]
Vertical column used as characters delimiter seems to be hidden

`set colorcolumn="80"`

**Comment by loctvl842** [comment]
Is this [#14](https://github.com/loctvl842/monokai-pro.nvim/issues/14) the same problem to you

**Comment by marnas** [comment]
That's correct, thank you for the pointer.

His solution also worked for me, I only changed the color for better integration with the theme.

`vim.api.nvim_set_hl(0, "ColorColumn", { ctermbg = 0, bg = "#262626" })`
