### ISSUE TITLE
Cannot enable cursorcolumn = true with monokai-pro theme

### ISSUE THREAD

**Issue by morenohernan** [loctvl842/monokai-pro.nvim#23]
Hi, I've checked the doc and I don't see where to enable the cursorcolumn 
I already enabled it in my vim editor (astrovim)

**Comment by morenohernan** [comment]
Never mind found how-to
return {
      "loctvl842/monokai-pro.nvim",
      config = function()
        require("monokai-pro").setup({
          filter = "classic",

        plugins = {
          bufferline = {
            underline_selected = true,
            underline_visible = true,
          },
          indent_blankline = {
            context_highlight = "pro", -- default | pro
            context_start_underline = true,
          },
        },
          override = function(colors)
            return {
                    CursorColumn = {
                      bg = colors.base.dimmed5,
                    },
              }
          end
        })
      end,      
}

**Comment by Grazfather** [comment]
Why is it that the default cursorcolumn is set to bg? It means that the default basically disables this functionality. Shouldn't it match cursorline?
