### ISSUE TITLE
Can't set octagon theme

### ISSUE THREAD

**Issue by CharlieCheckpt** [loctvl842/monokai-pro.nvim#3]
Hello, 
Thank your for porting this great color theme to neovim. It looks great.

I would like to set octagon version of monokai-pro but it does not seem to work. The color theme still looks lke [Pro](https://github.com/loctvl842/monokai-pro.nvim#Pro). 

As proposed in the README, I added the following lines to my `init.lua` : 

```lua
require("monokai-pro").setup({
	transparent_background = false, -- better set to false
	italic_comments = true,
	theme = "octagon", -- classic | octagon | pro | machine | ristretto | spectrum
	diagnostic = {
		background = true, -- highlight background of diagnostic
	},
    plugins = {
        bufferline = {
            underline_selected = true, -- better set `false` if you don't use kitty terminal
        }
    }
})
```

Am I missing something ?

**Comment by loctvl842** [comment]
sorry for not updating readme soon

**Comment by loctvl842** [comment]
> Got it ! It's because it should be `filter = octagon` in the setup function. The README should be updated.

sorry for not updating readme soon
