### ISSUE TITLE
Is there any way to disable plugins ?

### ISSUE THREAD

**Issue by dtk9289** [loctvl842/monokai-pro.nvim#30]
I'm using indent-blankline but when i use monokai-pro, it doesn't highlight anymore.
With indent-blankline plugin
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/48422877/5c1ab3e8-f251-42ed-aa26-a412ba55289a)
Without it
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/48422877/63cb3592-3e24-485c-83f2-38cafa487d86)

**Comment by loctvl842** [comment]
Ah it's simple. That's the default color of it. you can override the color of indentblankline.

```lua
require("monokai-pro").setup({
  ---@param c Colorscheme
  override = function(c)
    return {
            IndentBlanklineContextChar = { fg = "#ff0000" }, # or c.base.red
            IndentBlanklineContextStart = { sp = "#ff0000" },
  }
})
```

or simpler, using `pro` context_highlight

```lua
      monokai.setup({
        plugins = {
          indent_blankline = {
            context_highlight = "pro", -- default | pro
            context_start_underline = true,
          },
        },
      })

```

**Comment by loctvl842** [comment]
à bạn người Việt à

**Comment by dtk9289** [comment]
Bác cho hỏi luôn, sao để ở dòng if thì hiện mà chuyển xuống dòng dưới nó thì mất, bác có bị vậy ko
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/48422877/75c29fe7-164a-4791-a2dd-39a35eba50e5)
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/48422877/aff34cc2-fff4-4354-aa4b-6a50be786293)

**Comment by loctvl842** [comment]
![issue30](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/27af62f3-e096-4987-af51-85cacea41804)

Của tôi bình thường mà. Tôi dùng [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim)
