### ISSUE TITLE
Add more color differentiation

### ISSUE THREAD

**Issue by chrisgrieser** [loctvl842/monokai-pro.nvim#36]
Love the theme, but in comparison to other themes, I noticed that there is less differentiation in colors. For example, here `return`, other keywords like `if`, fields like `.caffeinate`, and the `=` all get the same color. Compare this to dawnfox (from nightfox.nvim), where the same four things all have different colors. 

![CleanShot 2023-05-27 at 12 53 57@2x](https://github.com/loctvl842/monokai-pro.nvim/assets/73286100/8101cd63-1cc3-4090-8856-d7782026f3d3)

![CleanShot 2023-05-27 at 12 57 00@2x](https://github.com/loctvl842/monokai-pro.nvim/assets/73286100/c5c0af59-736e-4240-96b7-cbdab598bf52)

**Comment by loctvl842** [comment]
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/d3536465-92fa-4713-b9ac-e97ab0195efe)

Here is mine. Can you try again.

**Comment by chrisgrieser** [comment]
The orange comes cause they are global I think. 

And the red for the fields are probably lsp semantic highlighting. 

Anyway, it looks the same

**Comment by loctvl842** [comment]
Yah, I just want to keep the colorscheme like the [original](https://monokai.pro/)
