### ISSUE TITLE
[Feature Request/Question] make theme work with `wilder` plugin

### ISSUE THREAD

**Issue by CharlieCheckpt** [loctvl842/monokai-pro.nvim#4]
Hello,

I'm using [wilder](https://github.com/gelguy/wilder.nvim) to have command line auto completion.
This plugin adds a list of possible completions when searching or starting to type commands (`:` or `/` or `?`).

Right now, we can't see the suggestions with `monokai-pro` theme, as the completion text is black on a black foreground.

Example of wilder with monokai-pro. We can't see any suggestion.
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/10373261/209071566-e5f509c4-bb81-4c1d-9e64-3d3a580ac199.png">

Example of wilder with sonokai. We can see wilder suggestion just above my command: 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/10373261/209072091-9914bee9-7cee-4752-8f2f-8aae96355a12.png">

Is it possible to support `wilder` ? 
Or is there any tweak I can make to the `monokai-pro` config to change the text color of the suggestions text ?

Thank you for the plugin.

**Comment by loctvl842** [comment]
supported `wilder`.  Recommend you use this:
```lua
cmp.setup.cmdline("/", {
	mapping = cmp.mapping.preset.cmdline(),
	sources = {
		{ name = "buffer" },
	},
})

cmp.setup.cmdline(":", {
	mapping = cmp.mapping.preset.cmdline(),
	sources = cmp.config.sources({
		{ name = "path" },
	}, {
		{ name = "cmdline" },
	}),
})

```
