### ISSUE TITLE
Enable theme selection through :Telescope colorscheme

### ISSUE THREAD

**Issue by ema2159** [loctvl842/monokai-pro.nvim#41]
Hi. Thanks a lot for this package, it has been my daily driver for a couple of months now and I really enjoy using it.

Like many other Neovim users, I use Telescope for many purposes, and one functionality I find myself using quite often is the `:Telescope colorscheme` command. I am aware that the `:MonokaiProSelect` command exists, however, I would like to be able to select among the Monokai Pro variants within Telescope. Several theme plugins with variants (i.e. Tokyo Night, Rose Pine, Kanagawa) expose their variants as individual themes. Would it be possible to offer such functionality? Please let me know what you think.

Thanks a lot for your work!

**Comment by loctvl842** [comment]
Please try the latest release.

**Comment by ema2159** [comment]
Perfect! That's it. Thanks a lot.
