### ISSUE TITLE
Overwritten devicons not compatible with nerd fonts v3

### ISSUE THREAD

**Issue by mvaladas** [loctvl842/monokai-pro.nvim#51]
With nerd fonts v3 there are a significant number of icons that just look wrong.

<img width="394" alt="image" src="https://github.com/loctvl842/monokai-pro.nvim/assets/120122/7146bacc-fac0-441b-92d2-6fff8f11b1c0">

The fix should just be updating with the current nvim-web-devicons definitions.

**Comment by loctvl842** [comment]
I'll update this later. Because highlighting devicons is just being tested, many icons isn't highlight. Therefore, it is disabled by default.

**Comment by mvaladas** [comment]
I don't see any more issues on my end. Thanks for the quick reply.
