### ISSUE TITLE
Is there a way to make nvim-tree transparent?

### ISSUE THREAD

**Issue by solidiquis** [loctvl842/monokai-pro.nvim#55]
Wondering if it were possible to get `nvim-tree` to be transparent along with the transparent background. Thanks for monokai-pro!

<img width="1725" alt="Screen Shot 2023-05-30 at 9 51 33 PM" src="https://github.com/loctvl842/monokai-pro.nvim/assets/45523555/0e1e586c-6a52-4067-ae83-a8c4a8da310b">

**Comment by loctvl842** [comment]
Yes which terminal are you using?

**Comment by solidiquis** [comment]
Wezterm

**Comment by loctvl842** [comment]
you have to add `nvim-tree` to `background_clear`.
Here are default of `background_clear`:
```lua
monokai.setup({
  background_clear = {
    -- "float_win",
    "toggleterm",
    "telescope",
    "which-key",
    "renamer",
    "notify",
    -- "nvim-tree",
    -- "neo-tree",
}

uncomment `nvim-tree` to clear the background

**Comment by solidiquis** [comment]
No dice :[ 
<img width="1881" alt="Screen Shot 2023-05-31 at 11 06 57 AM" src="https://github.com/loctvl842/monokai-pro.nvim/assets/45523555/1a38e1ea-eb83-4128-b38c-d8c5dea48259">

**Comment by loctvl842** [comment]
You have to make your terminal transparent by itslef and add `nvim-tree` to background_clear`

Please change `transparent_background` to `true`

Here is the result:

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/e169411d-98b6-488d-9121-007ffb6b82ee)

The left is kitty terminal and the right is alacritty

**Comment by solidiquis** [comment]
Unfortunately even on Alacritty I couldn't get this to work. My current work-around will be to just `vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "none" })`. Closing issue!
