### ISSUE TITLE
ColorColumn should be different than Normal background

### ISSUE THREAD

**Issue by jemag** [loctvl842/monokai-pro.nvim#61]
Currently ColorColumn background is the same as the Normal background:
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/7985687/b75268be-b44d-4381-b77e-ea880ce4d240)

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/7985687/a501222e-4f84-4f6a-b950-740919126633)

Which essentially makes enabling CursorColumn useless by default. 
Would be nice to have same value as CursorLine:
 `CursorLine     xxx guibg=#313443`

I am aware of both https://github.com/loctvl842/monokai-pro.nvim/issues/16 and https://github.com/loctvl842/monokai-pro.nvim/issues/14, however users that do not like to use  ColorColumn should have it disabled appropriately using 
`set cc=` 
or `vim.opt.colorcolumn=""`
So having the ColorColumn a different color will not impact them anyway.

**Comment by loctvl842** [comment]
I fixed it already. Please use the latest release
