### ISSUE TITLE
Support with treesitter.

### ISSUE THREAD

**Issue by AbdullahZubair-UW** [loctvl842/monokai-pro.nvim#65]
I was wondering if this plugin can somehow be updated to better compliment treesitter? I'm getting sub optimal syntax highlighting with LaTeX at the moment.

**Comment by loctvl842** [comment]
Please try the use the latest update. I did support treesitter for latex. Please leave a comment.

**Comment by AbdullahZubair-UW** [comment]
Thanks! Looks great.
