### ISSUE TITLE
Request: Lualine Monokai Classic theme

### ISSUE THREAD

**Issue by huyhoang8398** [loctvl842/monokai-pro.nvim#67]
Is it possible to have Monokai classic theme for lualine?

**Comment by loctvl842** [comment]
Chào bạn, tớ có hỗ trợ cái monokai-classic cho cái lualine mà ta.

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/52324140-69b2-4ec6-b36f-0dfb07a0f358)

**Comment by huyhoang8398** [comment]
<img width="1680" alt="Screenshot 2023-07-09 at 22 12 53" src="https://github.com/loctvl842/monokai-pro.nvim/assets/25379882/05b5ee46-631d-4c8d-aa91-d5ca8af6d1d1">
Có cách nào để cái back ground nó trùng với phần editor k bạn, giống ảnh cuối với phần mô tả của bạn

**Comment by loctvl842** [comment]
có á bạn. Này config hơi lằng nhằng xíu, tại vì kh dùng override trong config đc. Mà bạn phải tự custom cái theme cho lualine luôn á. Chỉ cần custom cho `lualine` có cái background trùng với background của nvim là được
- Một tự custom thì có thể tham khảo của mình [tìm theme nha](https://github.com/loctvl842/nvim/blob/master/lua/tvl/config/lualine/init.lua)
- Dễ hơn nhưng mà không nên. Edit trực tiếp cái file `lua/lualine/monokai-pro.lua`:

```lua
monokai_pro.normal = {
  a = { bg = colors.base.yellow, fg = colors.base.black, gui = "bold" },
  b = { bg = colors.base.dimmed5, fg = colors.base.yellow },
  c = {
    -- bg = colors.statusBar.background,
    bg = colors.editor.background,
    fg = colors.statusBar.activeForeground,
  },
  x = {
    bg = colors.statusBar.background,
    fg = colors.statusBar.activeForeground,
  },
}
```

Mình sửa cái `c` trong `normal` á
