### ISSUE TITLE
Better support treesitter 

### ISSUE THREAD

**Issue by huyhoang8398** [loctvl842/monokai-pro.nvim#68]
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/25379882/ad004034-6419-4702-bade-e004978db4fb)

Co cach nao de giup treesitter highlight tot hon cho Dockerfile k nhi.
Minh expect phan args se duoc highlight mau khac

**Comment by huyhoang8398** [comment]
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/25379882/ab475a9b-8ee9-433f-b333-92860bce9dba)

**Comment by huyhoang8398** [comment]
Vi du 1 colorscheme khac 
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/25379882/b14e8724-495b-4433-bbf7-580d3df7926b)

**Comment by loctvl842** [comment]
I have just support this in the latest release. Please update and give me a review for this.

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/80513079/d7da0493-60f4-4445-a5de-09129f1131d9)

**Comment by huyhoang8398** [comment]
It works quite well now, but do you know why `cd` and `echo` has different color?
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/25379882/b421be22-d648-4ddd-a90a-e6294a8ede76)

**Comment by loctvl842** [comment]
Its builtin function. while go or dep is call function
