### ISSUE TITLE
Dart highlight

### ISSUE THREAD

**Issue by gruvw** [loctvl842/monokai-pro.nvim#79]
Dart is not highlighted properly:

![image](https://github.com/loctvl842/monokai-pro.nvim/assets/63407038/05cf4765-76d3-48e2-9354-df4a423e3a7a)

**Comment by fegyi001** [comment]
I have no issues with it, it looks fine on my machine (using `akinsho/flutter_tools.nvim`):

<img width="1678" alt="image" src="https://github.com/loctvl842/monokai-pro.nvim/assets/4125222/659bde76-213a-45ea-963b-a9f5c9239438">

**Comment by loctvl842** [comment]
Sorry for late reply. About Dart, I haven't used it and currently, I don't want to spend time setting Dart up. Anyway, you found your way, I'll try Dart later. Thanks a lot for using this colorscheme.
