### ISSUE TITLE
inlay hints barely visible

### ISSUE THREAD

**Issue by fegyi001** [loctvl842/monokai-pro.nvim#81]
With the new built-in feature of neovim, inlay hints can be viewed. 
But with this colorscheme it is hardly visible if visible at all:

<img width="1029" alt="image" src="https://github.com/loctvl842/monokai-pro.nvim/assets/4125222/af9d7dd0-a0cc-48f2-af2c-8070431122b7">

The inlay hints are there, just not visible enough: 
<img width="433" alt="image" src="https://github.com/loctvl842/monokai-pro.nvim/assets/4125222/7bae6bbc-abcc-4202-a9f7-7e00d5ef1c96">

Is it possible to alter the colorscheme, so that the inlay hints could be seen properly?

With tokyonight it looks just fine, but I'd like to use monokai pro.
<img width="1018" alt="image" src="https://github.com/loctvl842/monokai-pro.nvim/assets/4125222/cc0cb5bc-8940-4871-8207-b4bca3b1e6c2">

Thanks in advance!

**Comment by fegyi001** [comment]
Could I have any response on this? Is it a feature to be added in the future?

**Comment by loctvl842** [comment]
Oh sorry for late reply, I'll try to look into this as soon as possible, it's been a long time since the last time I used inlay-hint. I'll need some time config it again.

**Comment by loctvl842** [comment]
Please checkout the latest version. I did add highlight for `inlay hint`

**Comment by fegyi001** [comment]
It works, thanks a lot!

<img width="634" alt="image" src="https://github.com/loctvl842/monokai-pro.nvim/assets/4125222/12357152-ff36-4eb8-a4ed-75423cfb9297">
