### ISSUE TITLE
How to change color of Diagnostic messages

### ISSUE THREAD

**Issue by kaykhan** [loctvl842/monokai-pro.nvim#90]
I am trying to migrate from https://github.com/sainnhe/sonokai to this plugin theme.

How do i change the color of the diagnostic messsages, you can see in the "monokai-pro" screenshot that the error message is in the color "white" and the info message is in the color "blue"

I would prefer if the error message was red and the info message was gray ( like in the sonokai screenshot)

**monokai-pro**
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/5202527/606d21c2-b482-425e-ac2b-7c4ea044e180)

**sonokai**
![image](https://github.com/loctvl842/monokai-pro.nvim/assets/5202527/b06a382e-c0e9-4196-8a68-26e3931faa9b)

**Comment by kaykhan** [comment]
this was occuring as i had to add a bunch of custom stuff with sonokia once i removed that i worked.

but now im also playing around with 

```
		override = function()
					return {
						Normal = { bg = "#121212" },
						DiagnosticVirtualTextError = { bg = "#121212" },
					}
				end,
				```

**Comment by loctvl842** [comment]
can you describe more detail?
