### ISSUE TITLE
Differ the color of  Local variables, variable types, formal parameters and actual parameters

### ISSUE THREAD

**Issue by narutozxp** [loctvl842/monokai-pro.nvim#92]
my nevim theme is as follows. I wish all variable types have the same color(such as int and vector<t_segment_inf>)， besides, the color of Local variables should be different from formal parameters and actual parameters.
![M{226GJYR~TYM7UIOH39QRI](https://github.com/loctvl842/monokai-pro.nvim/assets/41829090/2bb81662-738b-49b6-8630-808690253c7a)

Just like the following pic came from vscode monokai pro.
![04C_Q(PI6GW8~G~V)ZYZYQL](https://github.com/loctvl842/monokai-pro.nvim/assets/41829090/f50f472d-2b71-4ede-86d1-852744bf03c2)
Do you have any tips to do that?
Thanks!

**Comment by loctvl842** [comment]
I agree with you that my colorscheme is kinda "white". Just did some tweaks on the highlights. Give the newest version a spin and drop a comment. Don't forget to enable `semantic token` and `treesitter`

**Comment by narutozxp** [comment]
It seems still a bug. 
![1MAC6O9Y5FN)4GR{3L@J87B](https://github.com/loctvl842/monokai-pro.nvim/assets/41829090/1c457795-8d6a-451a-b3fc-ae4d83cae33d)
Just look at the pic above, the var `num_sets` is still white which is inconsistent with the color of the actual parameters.
In my opinion, if all actual parameters have the same color which is different from the local var's, I could distinguish whether a var is an actual parameter or not quickly. I think it's helpful when my function body is too long.

**Comment by loctvl842** [comment]
It's not a bug, `neovim` is not `vscode`. `num_sets` in this case is validated as a parameter variable in `vscode` while in `neovim` it's just like any other normal variables.
