### ISSUE TITLE
Annoying log about nvim-web-devicons

### ISSUE THREAD

**Issue by Kerry-G** [loctvl842/monokai-pro.nvim#99]
Since the 1.19 release, there has been a log about enabling nvim-web-devicons for a better experience.

My expected behaviour when the setting `devicons` is set to `false` would be to not have such log. 

[This is the culprit log. 
](https://github.com/loctvl842/monokai-pro.nvim/blob/b49795aa8a0cb6596660dae31ac10a43eff2d33b/lua/monokai-pro/util.lua?fbclid=IwAR2to3y9EsJQ1qwBSiR2XP2KNIUdQMYHWDxHSTaBkfyezdhhMXl1arZky6Q#L191)

**Comment by loctvl842** [comment]
Sorry, i'll fix this today

**Comment by loctvl842** [comment]
@Kerry-G , Hi, I checked the code and it seems that no issues occurred. Could you please provide more information about how you encountered this error?

**Comment by ChemicalLuck** [comment]
I've elaborated slightly on @Kerry-G's comment in a PR #112, this seems intentional, it isn't an error but it looks extremely pushy for the user when this prompt appears on every start-up
